#spring.cassandra.connection.local.poolsize=4
#spring.cassandra.connection.remote.poolsize=0
#spring.cassandra.connection.maxrequests=1024
#spring.cassandra.heartbeat.interval=30
#spring.cassandra.metrics.interval.ms=5000
#spring.data.cassandra.read-timeout=5000
#spring.data.cassandra.connect-timeout=5000
##spring.data.cassandra.contact-points=127.0.0.2,127.0.0.3,127.0.0.4
##spring.data.cassandra.port=9042
##spring.data.cassandra.local-datacenter=ap-south-1
###spring.data.cassandra.config=classpath:application-ycql.conf
##spring.data.cassandra.keyspace-name=kv
##spring.data.cassandra.username=cassandra
##spring.data.cassandra.password=cassandra