datastax-java-driver {
  advanced.connection {
    pool {
      local.size = 4
      remote.size = 0
    }
  }
  advanced.metrics {
      session {
        enabled = [
          connected-nodes,
          cql-requests,
          cql-client-timeouts,
        ]
      }
      node {
        enabled = [
          pool.open-connections,
          pool.available-streams,
          pool.in-flight,
          errors.request.write-timeouts,
          errors.request.read-timeouts,
          retries.total,
          retries.aborted
      ]
      cql-messages {
			highest-latency = 2 seconds
      	}
      }
      factory {
      	class = MicrometerMetricsFactory
      }
  }
  basic.load-balancing-policy {
  	class = PartitionAwarePolicy
  }
  basic.application {
  	name = boot-ycql-app
  }
}